# ------------------
# database settings
# ------------------

DB_CONN_STRING: "postgres://postgres:<pass>@<user>:<port>/postgres?sslmode=disable&search_path=<schema>"
DB_SCHEMA: "<schema>"
DB_RECREATE_TABLES: true
DB_QUERY_TIMEOUT: 3000s


# ------------------
# service settings
# ------------------

APP_PORT: 8083
APP_LIMIT_BODY_SIZE_IN_BYTES: 1048576